import hpsv2
# imgs_path can be a list of image paths, with the images generated by the same prompt
# or image path of string type
# or image of PIL.Image.Image type
#imgs_path = [r"D:\HPSv2-master\pictures\Orc2.jpg", r"D:\HPSv2-master\pictures\Orc1.jpg", r"D:\HPSv2-master\pictures\Orc3.jpg"]
imgs_path = [r"D:\HPSv2-master\hpsv2\images\attacked scary glowing ghost pirateship.png"]

prompt = 'scary glowing ghost pirateship with skeleton crewmembers in a tempest under a skull shaped moon by dan mumford and aleksi briclot, impactful rimlighting.'

result = hpsv2.score(imgs_path, prompt, hps_version="v2.1")
print(result)
